### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by johanhar** [SwiftyBeaver/SwiftyBeaver#128]
My Cartfile:

```
github "SwiftyBeaver/SwiftyBeaver"
```

My Cartfile.resolved:

```
github "SwiftyBeaver/SwiftyBeaver" "0.6.5"
```

After running `carthage update` and dragging the SwiftyBeaver.framework file over to Linked Frameworks and Libraries I get this error:

```
ld: .../myapp/Carthage/Build/iOS/SwiftyBeaver.framework/SwiftyBeaver compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by skreutzberger** [comment]
Please check the latest commit on master, I think it solved the Carthage error. If not then please try the swift3 branch.

**Comment by johanhar** [comment]
Carthage looks for a tag and version, not branch. Error is still there

**Comment by skreutzberger** [comment]
Sorry for the delayed response. As far as I remember, Carthage has an issue with branches so you may not be able to import the swift3 branch via Carthage. 

I also asked the other contributors on [https://slack.swiftybeaver.com](https://slack.swiftybeaver.com) and am waiting for an answer. PS: you can join there, too. It will expedite the help.

**Comment by skreutzberger** [comment]
Oh, I maybe found the issue by a simple googling 😳

Can you just add "swift 3" at the end of your Cartfile as described at [http://bit.ly/2bEtSwB](http://bit.ly/2bEtSwB)?

**Comment by skreutzberger** [comment]
## How to use Carthage with SwiftyBeaver Swift 3 branch

At first, you need to switch your xcodebuild command to use the new Xcode 8 beta app instead of the default Xcode 7.3.1. On my Mac that can be done via `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`. Just use the path to your downloaded Xcode-beta.app.

You can check if the switch to the new Xcode 8 build did work via `xcodebuild -version` which should show Xcode 8.0.

Now, please add the following line to the Cartfile of your Swift 3 compatible project to use the latest commit from SwiftyBeaver's swift3 branch:

`github "SwiftyBeaver/SwiftyBeaver" "swift3"`

After saving the Cartfile, just run Carthage with  `carthage update --platform iOS` or whatever platform you are using and link the built framework as you usually do.

Happy Swift 3 🎉

**Comment by johanhar** [comment]
Thanks! It works ✌️

**Comment by rlaferla** [comment]
Can someone update the README on the home page so that for Swift 3, it says:

github "SwiftyBeaver/SwiftyBeaver" "swift3"

**Comment by skreutzberger** [comment]
Setting the swift3 branch is not necessary anymore. Since a month or so the master branch serves swift 3.
