### ISSUE TITLE
How can I get color in all my log messages?

### ISSUE THREAD

**Issue by githotto** [SwiftyBeaver/SwiftyBeaver#164]
I installed the most recent SwiftyBeaver (1.1.1) using the cocoa-pod 1.1.1. However in my Xcode-debug-console as well as the default swiftybeaver.log I do NOT see any colors.

The contents of swiftybeaver.log is as follows:
20:38:11.630 [38;5;251mVERBOSE[0m AppDelegate.setupSwiftyBeaver():36 - not so important
20:38:11.634 [38;5;35mDEBUG[0m AppDelegate.setupSwiftyBeaver():37 - something to debug
20:38:11.634 [38;5;38mINFO[0m AppDelegate.setupSwiftyBeaver():38 - a nice information
20:38:11.634 [38;5;178mWARNING[0m AppDelegate.setupSwiftyBeaver():39 - oh no, that won’t be good
20:38:11.635 [38;5;197mERROR[0m AppDelegate.setupSwiftyBeaver():40 - ouch, an error did occur!

whereas the Xcode (8.1 8B62) shows:

20:38:11 VERBOSE not so important
20:38:11 DEBUG something to debug
20:38:11 INFO a nice information
20:38:11 WARNING oh no, that won’t be good
20:38:11 ERROR ouch, an error did occur!

also without any colors.
Somebody knows how to fix this, or am I missing an instructions from SwiftyBeaver's homepage?

**Comment by skreutzberger** [comment]
Hi,

these weird special chars are color symbols used by the XcodeColors plugin for Xcode 7. They are not visible in Xcode 8 because Xcode plugins are not allowed anymore with Xcode 8. We actually removed that part from the documentation to avoid confusion with Xcode 8 users.

Under Xcode 7 you can turn these cryptic symbols into color by installing the [XcodeColors plugin](https://github.com/robbiehanson/XcodeColors). Under Xcode 8 the color comes via colored emojis built-in. 

Good to know: if you log to file / use the file destination then you always have color built-in independent on what Xcode version you are using.

Hope that helps?

**Comment by githotto** [comment]
Hi,
Thanks for your reply, but still some questions remain:
1. How can I get the colored/emojis in my Xcode8?
2. If I view the (default) generated swiftybeaver.log file I still don't see Colors (I tried Atom/TextWrangler/Console to view the file)?
3. When I look on the SwiftyBeaver (main)website I still see the claim that you can get colored output, which I still don't see using the above Xcode8-debug-console of default generated log-file.

Probably I'm missing some instructions (on SwiftyBeavers home-page) or additional software-tools?!

**Comment by skreutzberger** [comment]
Hi,

here is my reply:

1. It is default in Xcode 8 with Swift 3 and works out of the box. It may be the case that the combination Xcode 8 & Swift 2.3 may not work in terms of colors but using Swift 2.3 is anyway not recommended anymore following Apple and the Swift guys.
2. It works with every modern Terminal app like Apple's Terminal.app and iTerm2. You can tail with a command like `tail -f /tmp/my.log` in case your log file is in /tmp/my.log.
3. Please see above :)

In general, please mind the [docs](http://docs.swiftybeaver.com). Color is active on default for file and console.
