### ISSUE TITLE
clarify one of the tests + filter definition

### ISSUE THREAD

**Issue by rajatk** [SwiftyBeaver/SwiftyBeaver#212]
for the test here: https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Tests/SwiftyBeaverTests/BaseDestinationTests.swift#L510

`
        let destination = BaseDestination()
        destination.minLevel = .error

        destination.addFilter(Filters.Path.contains("/ViewController", minLevel: .debug))
        destination.addFilter(Filters.Function.excludes("myFunc", minLevel: .debug))
     
        // not excluded, but above minLevel
        XCTAssertFalse(destination.shouldLevelBeLogged(.error,
                                                      path: "/world/OtherViewController.swift",
                                                      function: "otherFunc",
                                                      message: "Hello World"))
`

Is this correct. If I understand the definition of filters correctly, anything at or above the global min level should pass and be logged right?

**Comment by skreutzberger** [comment]
yes, you are right, the message should be logged because the filters are not required and the minLevel is error. it seems we have a logic issue in the the filters. can you fix it without changing the whole thing? AFAIR we did a small change on filters a month ago or so, maybe that introduced that wrong behavior.

**Comment by rajatk** [comment]
pushed a PR #215
