### ISSUE TITLE
ElasticSearch Destination

### ISSUE THREAD

**Issue by kostyan5** [SwiftyBeaver/SwiftyBeaver#247]
Any interest in being able to send logs to ElasticSearch?  I realize it may compete with your platform but it would be nice to keep logs from all our services in one place.  I plan on adding ElasticSearch destination and if you are interested in supporting that, I'll be glad to issue a pull request when I'm done.

**Comment by skreutzberger** [comment]
We are already working on something similar since some months which avoids storing the ElasticSearch credentials on your phone. It also uses end-to-end encryption which is important for countries like China, the EU or privacy-concerned industries.

The destination will be open-source and the server component will have a freemium model with the paywall kicking at when used used on a massive scale. Private beta is starting soon.

So back to your question: if you don’t mind let's talk about it in 2 months again when we can see clearer where we can join forces in our support for ElasticSearch.

**Comment by kostyan5** [comment]
I finished up basic ElasticSearch destination.  I realize you may not be ready for it yet but I issued a PR anyway.  Even if you don't end up merging it, hopefully you can use some of that work to speed up your development.
