### ISSUE TITLE
Log file rotation WIP

### ISSUE THREAD

**Issue by DivineDominion** [SwiftyBeaver/SwiftyBeaver#273]
I bit the bullet of #7 and implemented a `RotatingFileDestination` myself in a couple of hours. See the PR at #272.

Stuff I want to do:

- [x] Add a `DeletionPolicy` that cleans up old files after a couple of dates.

That's all I need to use the feature. I'm releasing an app very soon and cannot pour more time into this than the bare minimum. So others can pick up and fill in the missing parts, I suggest to create a new WIP branch and merge my PR into that, so that others can create PRs against this work-in-progress branch, for example:

- [ ] Test DateFormatter edge cases, foreign locales and calendars
- [ ] Adapt test for iOS (currently tests run in macOS only)
- [ ] Add more rotation intervals?

**Comment by skreutzberger** [comment]
looks good, thanks!

**Comment by Jeehut** [comment]
@skreutzberger Why was this closed without a comment? There still seems to be no solution to #7 or #366. We'd love to somehow restrict the amount of log entrieskept to 24 hours though and it doesn't seem to be easy ...

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years.
