### ISSUE TITLE
SBPlatformDestination not sending log items

### ISSUE THREAD

**Issue by simonhessner** [SwiftyBeaver/SwiftyBeaver#277]
Hi,

I want to enable logging to the encrypted cloud server using SBPlatformDestination  and I already got it working (log messages were shown in the SwiftyBeaver Mac App) but suddenly it stopped working and I don't know why. So I enabled showNSLog and this is what I see:

> SBPlatform: saving 'AppDelegate didFinishLaunchingWithOptions' to file:///var/mobile/Containers/Data/Application/blablabla/Documents/sbplatform_entries.json
> SBPlatform: current sending points: 0
> SBPlatform: initialSending: 0 points is below threshold but json file already has 22 lines.
> SBPlatform: reset points to 0
> SBPlatform: Encrypting 11016 log entries ...

This is all I can see, there are not errors shown and the log entries are not visible in the app.

Since it worked with these settings before, I think the problem occurs inside SwiftyBeaver and is not because I misconfigured something. Just to be safe, this is how I use the logger:

```
let platform = SBPlatformDestination(appID: "...", appSecret: "...", encryptionKey: "...")
platform.showNSLog = true
platform.sendingPoints.threshold = 1
log.addDestination(platform)
```

Do you have an idea why it does not work? Maybe there are too many items to be encrypted? But how can I delete them?

My SwiftyBeaver version is 1.5.0

**Comment by simonhessner** [comment]
I deleted the app from my device in order to get rid of the unsent log messages and then restarted the app. At the beginning it worked (log messages were correctly shown in the Mac app) but then it took the iOS app several minutes to process (encrypt and send) the log entries.

So I think SwiftyBeaver doesn't like apps that log very much? At the moment I'm logging every little thing in my app because there are random crashes which I cannot reproduce.

How many log messages per second are the limit I can use with SwiftyBeaver in order to prevent lags / not sending messages at all?

**Comment by skreutzberger** [comment]
You are right, you should not log massively to the Platform destination since it can become a drain on your user's device, especially if it is an old one. SwiftyBeaver is running itself on a low-priority thread to avoid to negatively impact the performance of your app but the encrypting and sending of logs just can take time.

Additionally the receiving crypto cloud has thresholds to avoid to be overwhelmed with logs from a single device.

To solve your issue I recommend 2 things:
1. try to log a bit less or give it more time to send the logs
2. try the SwiftyBeaver Enterprise trial which lets you log to your own Elasticsearch server. That removes the potential throttling on the cloud side and is the common solution for larger companies who log a lot, have many users or have high compliance regulations. Here is a link: http://docs.swiftybeaver.com/


To learn more and discuss further optimizations please signup at our Slack channel http://slack.swiftybeaver.com/ or contact us via email hello@swiftybeaver.com
