### ISSUE TITLE
Mac App doesn't show context.

### ISSUE THREAD

**Issue by Spr-Luis** [SwiftyBeaver/SwiftyBeaver#297]
The Mac application doesn't show the context. How can I fix it?

**Format**
```
console.format = "$DHH:mm:ss $L: $M $X"
```

Log

```
log.info("Route Started")
log.info("ID:", context: currentRoute?.id ?? -1)
log.info("Origin:", context: currentRoute?.origin.name ?? "NA")
log.info("Destination:", context: currentRoute?.destination.name ?? "NA")
log.info("Departure:", context: currentRoute?.departureDate.toString(with: "dd-MM-yyyy HH:mm") ?? "NA")
log.info("Next Order:", context: nextStation)
log.info("Next Station:", context: next?.stop.name ?? "NA")
```

**Xcode Print**
```
15:08:00 💙 INFO: Route Started
15:08:00 💙 INFO: ID: 37580
15:08:00 💙 INFO: Origin: Plaza Carso
15:08:00 💙 INFO: Destination: Live Aqua (Arcos)
15:08:00 💙 INFO: Departure: 23-05-2018 11:00
15:08:00 💙 INFO: Next Order: 1
15:08:00 💙 INFO: Next Station: Plaza Carso
```

**Mac App**

<img width="300" alt="captura de pantalla 2018-05-23 a la s 15 10 21" src="https://user-images.githubusercontent.com/5206221/40448546-72d24852-5e9b-11e8-8f74-b3971666d33c.png">

**Comment by skreutzberger** [comment]
That is expected behavior. The Mac App does not support context.

**Comment by jyounus** [comment]
@skreutzberger is there a particular reason for this? 

It would be great if context could be supported for the Mac app. 
This way it would allow us to filter logs based on the additional tags/context provided (ie if I only want to look at logs with a "Network" tag or "UI" tag, I can do so).

It would be super helpful. At the moment, I'm using a hack to append my custom tags as part of the logs (meaning I'm logging the following: "[content] | [message]") so that I can then filter in the Mac app. This doesn't always seem to work great. Native support for context in the Mac app would be much better (and searchable of course).

Is this something you'd consider adding?

**Comment by skreutzberger** [comment]
yes, it is considered and on the roadmap.
