### ISSUE TITLE
ConsoleDestination should use new os_log infrastructure if available

### ISSUE THREAD

**Issue by ileitch** [SwiftyBeaver/SwiftyBeaver#308]
Apple docs: https://developer.apple.com/documentation/os/logging
CocoaLumberjack implementation: https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDOSLogger.m

**Comment by skreutzberger** [comment]
We on purpose decided against it since it needs to have the console app open and you are not using the built-in console of Xcode (which is confusing to many developers).

Still, we could add support to the Console application, too. Would you like to maybe copy our console destination and rename and turn it into a destination which supports the console app? Naming we need to fix then on the fly :D

**Comment by andreyz** [comment]
I support @ileitch 's suggestion for two reasons:
1. `os_log` statements **are** mirrored in Xcode Console during debugging.
2. Universal system logging is the way that Apple wants to move on the platform, hence supporting it is just a question of time and staying relevant.

**Comment by skreutzberger** [comment]
Feel free to suggest a destination which uses os_log and still provides the same functionality and flexibility of our current console destination. I did not know that it is mirrored to Xcode's Console so it could be a natural evolution of the existing console destination. So a PR is welcomed 😊

**Comment by neoneye** [comment]
Check out Jean-Charles Sorin's [OSLogDestination](https://github.com/bill350/oslog-demo/blob/master/OSLog-demo/SwiftyBeaver/OSLogDestination.swift) with [blog post](https://medium.com/back-market-engineering/discovering-using-oslog-output-console-with-swiftybeaver-on-ios-54d7bfbe3b97) about how it works.
