### ISSUE TITLE
Add Kotlin framework for Android support 

### ISSUE THREAD

**Issue by OlexandrStepanov** [SwiftyBeaver/SwiftyBeaver#335]
Hello guys,

You have developed a nice tool for remote logging on iOS, but it's really missing Android support to have all-in-box logging solution for mobile app project.
Do you have any plans to implement such framework in near future?

Thanks in advance.

**Comment by skreutzberger** [comment]
Yes it is planned but more in the mid-term since we really are not Kotlin experts.

**Comment by nshoura** [comment]
Thank you very much for this amazing tool!
Is Kotlin/Android support this still considered?

**Comment by skreutzberger** [comment]
Yes but I guess it should come from other contributors

**Comment by nickprkins** [comment]
@skreutzberger, Any updates on adding Kotlin support for Android?

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
