### ISSUE TITLE
The State of Privacy for Device-Only Usage

### ISSUE THREAD

**Issue by Dschee** [SwiftyBeaver/SwiftyBeaver#336]
Following the WWDC 2019 talk about ["Great Developer Habits"](https://developer.apple.com/videos/play/wwdc2019/239/) we are taking the chance to check all our dependencies to ensure we are choosing them "responsibly" as explained in the talk in the "Manage" section.

One key information I'm not sure about when using SwiftyBeaver is about privacy. Since SwiftyBeaver has capabilities to send logs to a server to be able to see them later in the related app, we are completely ignoring that functionality and just want to use SwiftyBeaver as an on-device logging framework. So the big question for us is:

**How is SwiftyBeaver behaving by default** if not explicitly configured to send any data to any severs? And by which **precautions** does SwifyBeaver make sure that **no data is sent anywhere** if not explicitly configured to do so? E.g., do you have tests to ensure this?

It would be great to get answers to these questions, if possible including links to the appropriate code lines so we can check and ensure what's said is actually true ourselves.

Please note that in case SwiftyBeaver doesn't follow Apples (and our) guideline of "Privacy by Design" – meaning that the default and simplest usage isn't keeping user data private – than we will make sure to get away from SwiftyBeaver in favor of any other framework (or create our own) and additionally put it on our internal blacklist. This is not meant to be a threat or anything, I'm just hoping this will motivate you to think about privacy more in case you aren't already.

**Comment by lgaches** [comment]
@Dschee By default, the `destinations` is empty https://github.com/SwiftyBeaver/SwiftyBeaver/blob/198ba76be9641bc9def18ff8554dbd0c874e58f5/Sources/SwiftyBeaver.swift#L28

If you're only using ` ConsoleDestination` everything stay on the device.

`SBPlatformDestination` is the only destination which sends the log to a server but you have to add it and configure it explicitly.

SwiftyBeaver is a small library, and it's open source, so you can read the code quickly and see yourself what is going on.

**Comment by Dschee** [comment]
Thanks, this sounds good.

As the README isn't mentioning the topic once, I felt like asking for it and to be sure this will stay how it is right now is important. Since there is also an [Enterprise](https://swiftybeaver.com/enterprise) version of SwiftyBeaver, I sensed that there was some interest in collecting data there. So it would be great if privacy was stated as a goal of SwiftyBeaver somewhere in the README. Of course only, if it actually is.

**Comment by skreutzberger** [comment]
Thanks @lgaches for your reply. 

@Dschee thanks for expressing your concerns. SwiftyBeaver is not collecting any data without you as a developer knowing about it. That's why it is open-source and developed in a simple way to be easy to inspect and check what it is actually doing under the hood.

The only sending to servers is done if you use the `SBPlatformDestination`. That destination is meant for production logging and on default it sends your logs plus additional device information *end-to-end encrypted* to our cloud service. Our cloud service can NOT decrypt your payload.

Instead, you install our Mac App and that Mac App downloads the encrypted logs from the cloud and decrypts and shows them to you. Additionally, the Mac App stores ALL data that downloads in a local SQLite database file on your computer so that you actually "physically" own your data.

The business model of SwiftyBeaver is to provide the most secure logging solution in the market and (as far as I know) we are the only logging solution which does NOT store your logs or additional user data unencrypted on their servers.

Our Enterprise offering is an even more secure solution where you are not using anymore our cloud service and Mac App but you send your end-to-end encrypted logs directly to your own servers and you store them in your Elasticsearch cluster. 

Feel free to reply if you need more info and thanks for your remark relating the missing information in the README which we need to improve.

**Comment by Dschee** [comment]
@skreutzberger Thank you for that detailed information. In fact, that information is so thorough and to the point, that I just copied your text and integrated it to the README. Here's the PR: #337.
