### ISSUE TITLE
Make threadName() method open public

### ISSUE THREAD

**Issue by LorienMan** [SwiftyBeaver/SwiftyBeaver#338]
Hello community!
I've recently faced a problem with threadName function as it produces empty string for main thread that is not what I really want. I'd like to override it and provide a proper value for my use case.

Best regards

**Comment by skreutzberger** [comment]
Hi, that request is too much of an edge case since no one else has ever asked for it. I would prefer keeping our public framework API as clean as possible. So we won’t do it for now.

**Comment by LorienMan** [comment]
Is there any adequate way of naming main thread in logs as something that makes sense or I've missed something? :)

**Comment by skreutzberger** [comment]
On default the main thread is an empty string and changing that now to `MAIN` could have bigger implications for user since it is changing the default behavior of how the general logging output works. But you know what? We can reconsider it when we work on the next major version of SwiftyBeaver where potentially bigger changes can be easier introduced.

**Comment by LorienMan** [comment]
Yeah, I understand that you should not change default behavior but that would be great if such a customization will appear.

I'll fork repo atm, ty for responses ✌️
