### ISSUE TITLE
Random crashes on iOS 13: FileDestination.saveToFile() - try line.write(to: ...)

### ISSUE THREAD

**Issue by zavsby** [SwiftyBeaver/SwiftyBeaver#345]
Periodically SwiftyBeaver crashes on logging in FileDestination.saveToFile() method:
`try line.write(to: url, atomically: true, encoding: .utf8)`
with error: "**Fatal error: Insufficient space allocated to copy string contents**".

We cannot reproduce it in debug for now, it reproduces only on our Beta version in Fabric. Also it only happens on iOS 13 Beta devices. As we can see crash happens in StringUTF8View.swift (Swift core lib) on this condition check:
`guard let written = _guts.copyUTF8(into: buffer) else {
      _preconditionFailure(
        "Insufficient space allocated to copy string contents")
    }`

PS: Crashes happen when the original strings to be logged are created in ObjC as NSString and next they are passed to Swift.

Could you please help with this? Thanks.

**Comment by skreutzberger** [comment]
Hmm, it seems maybe the conversion from NSString to String does not work in iOS 13 beta? Please keep and eye on it if it gets automatically fixed by the next beta build. Also please mind our  `xcode11-beta` branch.

**Comment by skreutzberger** [comment]
closing it for now. we can continue the conversation

**Comment by mltbnz** [comment]
found this issue since we are having some crashes to it when wanting to log to `FileDestination`
<img width="1358" alt="Screen Shot 2021-11-30 at 18 42 30" src="https://user-images.githubusercontent.com/14075359/144100327-f076e157-f6f2-4558-a5d7-15ffa46afc16.png">

Could it be that this happens due to simultaneous access disk access? I saw on other threads doing some disk jobs like cache cleaning
