### ISSUE TITLE
Save logs for 2 days only

### ISSUE THREAD

**Issue by cleverClosure** [SwiftyBeaver/SwiftyBeaver#366]
Can I clear previous logs and save logs only for last 2 days in the local file?

**Comment by skreutzberger** [comment]
No, the file destination is built very basic for the purpose of potentially extending its functionality in the app itself.

**Comment by MaxHasADHD** [comment]
Is this not a highly requested feature? I'm using the basic file destination and now I get 200MB log files which I can't even open and view on iOS because it's so large when I just need the past 24 hours or last 100 log lines. I think I finally figured out a way of trimming from the bottom anyways and plan to create my own destination which is just FileDestination with a few extra lines of code. I'm sure a lot of people would like that same functionality though since the end result will always be large log files unless it's cleared, so everybody would have to be writing the same extensions or force clear the file randomly and potentially lose data if they were sent a log right after clearing it.

**Comment by skreutzberger** [comment]
The FileDestination was never meant to be used in iOS app and more for macOS or server-side Swift projects. Handling a growing log file and and sending it "back home" on request is too complicated for most users and that's why the platform destination was created. In the end, the platform destination is a file destination on steroids with auto-cleanup, encryption, etc.

Feel free to use the FileDestination as simple foundation for your own custom file destination.

**Comment by brunomunizaf** [comment]
@skreutzberger if I get it right, FileDestination does auto-cleanup?

**Comment by skreutzberger** [comment]
Hi, yes, version 1.9.4 added logfile rotation

**Comment by brunomunizaf** [comment]
@skreutzberger Could you explain a bit of how it works? I can't seem to find documentation about it. I wonder how big will it wait till it needs to be cleaned-up.

**Comment by MattTimmons** [comment]
I would also like to know how rotation works. I may use the FileDestination to store local logs (it is a Mac app). But need to know how big / long they stay around.

**Comment by iadcialim** [comment]
Yes, documentation on how the rotation works would be good.
Right now, the comments here might need to be improved.
```
// LOGFILE ROTATION
// ho many bytes should a logfile have until it is rotated?
// default is 5 MB. Just is used if logFileAmount > 1
public var logFileMaxSize = (5 * 1024 * 1024)
// Number of log files used in rotation, default is 1 which deactivates file rotation
public var logFileAmount = 1
```
