### ISSUE TITLE
Missing log events in the Mac app

### ISSUE THREAD

**Issue by antonkarev** [SwiftyBeaver/SwiftyBeaver#401]
Hi, I'm testing the SwiftyBeaver on iPhone. 

When my code sends two or more log.info events in less than a second, the Xcode console shows them all, but the SwiftyBeaver Mac app only shows the first one. The platform.sendingPoints.threshold is set to zero. I have the personal plan.

How can I force all the log events to be visible in the Mac app?

**Comment by abdurrahmansanli** [comment]
I don't understand why this is even closed. I have the same problem since I started experimenting on this. More than half of my logs are missing. Whats the point of using this when it's simply unreliable? Why did you close this thread with no explanation?

**Comment by skreutzberger** [comment]
please get in contact via email since it is about the cloud service and not the open-source project itself. thanks!

**Comment by abdurrahmansanli** [comment]
How are you judging this being about the cloud service?

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
