### ISSUE TITLE
iOS 14 Local Network Permission

### ISSUE THREAD

**Issue by alexanderlucas** [SwiftyBeaver/SwiftyBeaver#403]
Testing my app with SwiftyBeaver on iOS 14, I discovered it requires the new Local Network permission to work and wondered if that was strictly necessary. I was also wondering what in logging to the SwiftyBeaver platform was causing it.

Thanks!

**Comment by TorchedPoseidon** [comment]
I would like to know as well.

**Comment by TorchedPoseidon** [comment]
So far I've been able to confirm it's tied to the cloud option, but I haven't been able to find what in https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SBPlatformDestination.swift is causing it. Simply connecting to an api online shouldn't cause this permission prompt.

**Comment by ryoustra** [comment]
I ran into this issue and poked around a bit. It appears to be due to this line in SBPlatformDestination: 

`        details["hostName"] = ProcessInfo.processInfo.hostName`

I imagine querying the hostName is akin to sniffing around the local network, and iOS 14 throws the permissions dialog here.

I don't know the SwiftyBeaver code well enough, but am wondering if this is just used for its own analytics??? 

But at any rate, I temporarily got around the issue by substituting a placeholder string for the hostName dictionary entry.

**Comment by skreutzberger** [comment]
That is an interesting finding! Is it still an issue? If yes then can you maybe do a PR which gets rid of `ProcessInfo.processInfo.hostName`? it is just a convenience for the Mac App.

**Comment by benjamincombes** [comment]
Hi @skreutzberger, do you know when it will be published? iOS 14 is now live, and it's impossible to send an update to the AppStore with a scary popup on first app start for all users... Thanks!

**Comment by skreutzberger** [comment]
A new version of SwiftyBeaver goes live in 3-4 hours.

**Comment by skreutzberger** [comment]
Version 1.9.2 is live now and should cover all iOS 14 issues. Please have a look and test it out. Thanks for feedback!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.

**Comment by alfredcc** [comment]
https://github.com/SwiftyBeaver/SwiftyBeaver/blob/master/Sources/SBPlatformDestination.swift#L483
