### ISSUE TITLE
README Link is broken for log format

### ISSUE THREAD

**Issue by sonrohan** [SwiftyBeaver/SwiftyBeaver#405]
I have a PR for this here: https://github.com/SwiftyBeaver/SwiftyBeaver/pull/404

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years.
