### ISSUE TITLE
Xcode 12 build warning - 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by gabors** [SwiftyBeaver/SwiftyBeaver#419]
Hi when building with Xcode 12 GM I get this build warning

The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Looking at the SwiftyBeaver project file it does indeed specify 8.0

Will there be a framework update?
I'm integrating using SPM.

Thanks in advance!

**Comment by skreutzberger** [comment]
Thanks for the PR, a new version of SwiftyBeaver goes live later today.

**Comment by skreutzberger** [comment]
Version 1.9.2 is live now. Please have a look and test it out. Thanks for feedback!

**Comment by gabors** [comment]
Thanks @skreutzberger for merging and releasing so quickly.
I'll switch back to your repo and test it out.

**Comment by gabors** [comment]
Seems to be working well. @skreutzberger

**Comment by skreutzberger** [comment]
thanks for the quick feedback, I am closing the ticket for now.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
