### ISSUE TITLE
Add context to the cloud logs

### ISSUE THREAD

**Issue by horsejockey** [SwiftyBeaver/SwiftyBeaver#424]
I read in another closed issue that you are not able to change the formatting of the cloud logs. This does not seem to be well documented. Since the format can not be changed I am requesting that the context information be added to the cloud logs and displayed in the Mac App.

**Comment by skreutzberger** [comment]
yes, it is on the list. thanks!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
