### ISSUE TITLE
open vs public permission for custom()

### ISSUE THREAD

**Issue by adamwulf** [SwiftyBeaver/SwiftyBeaver#425]
I would like to extend `SwiftyBeaver` with some custom formatting options not available through the `format` string. My initial idea was to:

```swift
class MyLogging: SwifyBeaver {
     override class func custom(level: SwiftyBeaver.Level, message: @autoclosure () -> Any, file: String = #file, function: String = #function, line: Int = #line, context: Any? = nil) {
          .... custom formatting stuff here ....
          super.custom(...)
     }
}
```

However, that gives me the compile error `Overriding non-open class method outside of its defining module`

Changing the `custom()` method to `open` from `public` would do the trick.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
