### ISSUE TITLE
Direct API Access 

### ISSUE THREAD

**Issue by hardikdevios** [SwiftyBeaver/SwiftyBeaver#426]
We have succssfully integrated the SwiftyBever on iOS and want to replicate the same thing in Android, but as there is no SDK for Android so we have decided to call the direct API using the required parameter and Headers,
API:
`https://api.swiftybeaver.com/api/entries/ (POST)`
```
Authorization:Basic ************ourKey************
Content-Type:application/json
Accept:application/json
Content-Length:1145671
```
and 
`{"payload": "Ourpayload"}
`

And it gives 200 in response with
```
{
    "data": {
        "uri": "8Z4MDLA"
    }
}

```
**But those logs are not showing in the Cloud, any idea why this is not showing in Mac app?**

**Comment by skreutzberger** [comment]
the logs need to be of the right format and also need to be encrypted (see SBPlatformDestination)

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
