### ISSUE TITLE
Xcode 12 & iOS 14 (Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler)

### ISSUE THREAD

**Issue by xtravanta** [SwiftyBeaver/SwiftyBeaver#427]
Hi,

After updating my iPhone to iOS 14 i also needed to update my Xcode an after that i can't compile the code anymore because it gives me this error:

**import SwiftyBeaver  ///Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler**

Can you guys help me with this?

Thanks in advance.

**Comment by skreutzberger** [comment]
It seems to use SwiftyBeaver which was compiled with Swift 5.2.4. Can you maybe remove SwiftyBeaver and then add it again?

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
