### ISSUE TITLE
ARM DTK Support

### ISSUE THREAD

**Issue by appsird** [SwiftyBeaver/SwiftyBeaver#428]
Would be really nice to have the new ARM processor support currently available in the DTK.

Let me know if this is available, or any plans.

**Comment by skreutzberger** [comment]
It is not planned, yet but feel free to add a pull request to add it.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
