### ISSUE TITLE
Redundant swift checks

### ISSUE THREAD

**Issue by KartikSatoskar** [SwiftyBeaver/SwiftyBeaver#431]
@skreutzberger 
In project, I am finding several `#if swift(>=5)` swift compiler checks. Is there any specific reason for having this check?
Since same code is supporting on `swift<5` versions (though I checked on `swift4` and `swift4.2`).
If these checks turn out to be redundant, should I raise PR to remove those?

**Comment by skreutzberger** [comment]
There were some things which were not supported by Swift below Swift 5. Some things also just worked for Swift 4.2 and not Swift 4. So as long as things are working please leave them as they are. Staying backwards-compatible is a pain.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
