### ISSUE TITLE
Add option to stop file:line logging

### ISSUE THREAD

**Issue by bnazaruk** [SwiftyBeaver/SwiftyBeaver#436]
Hi there, 

I quickly checked the source and noticed that there's no option to have no file:line stuff in the log. It would be nice to add it.

**Comment by skreutzberger** [comment]
you can achieve it by using a custom logging format: https://docs.swiftybeaver.com/article/20-custom-format

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
