### ISSUE TITLE
Enabling SBPlatformDestination will trigger iOS 14's Local Network usage privacy warning

### ISSUE THREAD

**Issue by biogerm** [SwiftyBeaver/SwiftyBeaver#437]
Since my app got rejected, it took me two nights to figure out that it's the SBPlatformDestination that triggers this new iOS 14 warning:

`"xxx" would like to find and connect to devices on your local network.`

Is there any reason why SBPlatformDestination needs to access local network and can you remove this dependency?

BR
An Chin

**Comment by SteveBlackUK** [comment]
@biogerm - Confirming you have updated to 1.9.2?  That fixed it for me!

**Comment by biogerm** [comment]
@SteveBlackUK  you are probably right! I was on 1.9.1 and after switching to 1.9.2, the warning message wasn't shown any more!

**Comment by skreutzberger** [comment]
good stuff!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
