### ISSUE TITLE
SwiftyBeaver intalled with SPM disabled my debugger

### ISSUE THREAD

**Issue by cmouline** [SwiftyBeaver/SwiftyBeaver#438]
Version : 1.9.3
Xcode : 12.0

I'm currently moving from Carthage to SPM. But since I installed SwiftyBeaver 1.9.3 with SPM I can't get the variables informations I used to have in the debugger (when I hit a breakpoint for example).

Any clue why ?

**Comment by skreutzberger** [comment]
No, unfortunately not.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
