### ISSUE TITLE
Getting time out when trying cloud

### ISSUE THREAD

**Issue by vinamelody** [SwiftyBeaver/SwiftyBeaver#439]
Hi, I'm getting this error with the cloud.

```
2021-02-11 23:48:48.402964+0800 MyApp[12042:15978674] Task <FA393617-0C7F-4E0C-9738-BB04C601714B>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x600002dd2160 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.swiftybeaver.com/api/entries/, NSErrorFailingURLKey=https://api.swiftybeaver.com/api/entries/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
```

Implementation:

```swift
extension MaintenanceManager: UIApplicationDelegate {

    public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {

        let cloud = SBPlatformDestination(appID: "111", appSecret: "111", encryptionKey: "111")
        let console = ConsoleDestination()
        log.addDestination(cloud)
        log.addDestination(console)

        return true
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        self.connect()
    }
}

```

When I use `self?.log.info("Connected")` , the console shows the log and followed with that error

Thanks for helping!

**Comment by skreutzberger** [comment]
Sorry for the late reply. We had some issues with our cloud backend which were resolved. Please get in contact with support via email if you have further questions relating our cloud service. thanks!

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
