### ISSUE TITLE
Missing Logs

### ISSUE THREAD

**Issue by abdurrahmansanli** [SwiftyBeaver/SwiftyBeaver#445]
I wanted to love this so much. I was going to use this so I can log what's going on my tester colleagues phone with my app. 

However; most of the logs are missing. No matter for how long I'm waiting, I don't see 1/3 of the logs most of the time. (Mac app). I think there's a thread related issue with this. It's unreliable but why?..

**Comment by abdurrahmansanli** [comment]
I'm on the latest version. I've implemented it according to 'Usage' section. Even most of the logs there didn't appear. Some others did however...

**Comment by skreutzberger** [comment]
The cloud has some log throttling built in to avoid overwhelming the SwiftyBeaver Mac App:

the free plan allows 1.000 log messages per day, the personal plan 10.000 log message per day and the organization plan 25.000 log messages per day. Please get in contact with support via email if you have questions about your plan.

**Comment by abdurrahmansanli** [comment]
This is not about plans. You did not even ask about the issue I'm having. You are coming along with assumptions which does not fit a developer perspective.

Problem I've mentioned is not about log throttling. Even with the first install I wasn't able to get %80 of the logs. It might be about observation limitations. As some other thread mentioned; this happens if logs are sent so quickly like 5 logs in 1 second.

Anyway I see how you run things around. This is rubbish for me.

**Comment by skreutzberger** [comment]
I am sorry that I was not more helpful. It is just that we receive that kind of request occasionally and it is always caused by the log throttling. The framework is built in a way that it does not lose logs. All logs are sent to the cloud but the cloud may delete them if you are above your daily quota. Please post your logging setup (without credentials) to let me check if there are issues. sorry again!

**Comment by abdurrahmansanli** [comment]
I as well would like to apologize as I find myself in a tight schedule and I won't be able to collaborate in this anymore. For further reference I can tell:
- I applied the framework and created an account from scratch. Hence I can't be out of my daily quote.
- I've seen missing logs issue at first try. I could repeat the process many times afterwards.
- Whats happening is: my setup sends about 2-3 logs in 1 second. I think the framework OR cloud service works within 1 second intervals and drops any other logging happening let's say in milliseconds. 

If I find time in future I will come back and share more specific details with a demo project.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. SWIFTYBEAVER HAS NOT BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years. Feel free to contribute source code which makes it safer from your point of view and the contributors and I will consider merging it.
