### ISSUE TITLE
Question: Is this usable from Objective C?

### ISSUE THREAD

**Issue by bensarz** [SwiftyBeaver/SwiftyBeaver#62]
I love this library when using Swift. Has this lib been tested/used in ObjC?

**Comment by davidrothera** [comment]
At the moment none of the classes are exposed to ObjC, I don't know whether @skreutzberger is interested in adapting to use `@objc` wrapped functions/classes etc.

Having Swift code that is usable in ObjC limits you to not using some of the awesome things in Swift like structs, tuples, generators etc :frowning:

**Comment by bensarz** [comment]
@davidrothera I'd much rather convert the codebase I'm working on into Swift, but figured I'd ask anyway.

![](http://gif.co/vf5n.gif)

**Comment by skreutzberger** [comment]
Maybe the [SwiftyBeaver ObjectiveCWrapper](https://github.com/SwiftyBeaver/SBObjectiveCWrapper) is helpful?

**Comment by davidrothera** [comment]
I had a quick look through the code at the moment and we *could* support ObjectiveC however as I mentioned above it means we can't use some of the better features of Swift in future.

I personally would prefer a library never support ObjectiveC rather than support it now and then not support it in future when we decide that we want to use some more Swift features.

**Comment by skreutzberger** [comment]
@davidrothera :+1: we should keep the code future-proof == 100% Swift

Maybe the wrapper project could help Objective-C devs to migrate to Swift?

**Comment by bensarz** [comment]
My vote goes for 100% swift. I was asking the question more so because I'm stuck on this old ObjC codebase at the moment.
