### ISSUE TITLE
Consider allowing multiple logs to allow for separation of concerns

### ISSUE THREAD

**Issue by DanielAsher** [SwiftyBeaver/SwiftyBeaver#66]
SwiftyBeaver currently only provides for a single log target as its members are static. It is often useful to have multiple targets that can have log levels individually set:
```
let logView = SwiftyBeaver()
let logModel = SwiftyBeaver()
let logAudio = SwiftyBeaver()
```

**Comment by skreutzberger** [comment]
Thanks for your suggestion but I think it would complicate the general use of the framework to the average user. I understand your use case and minimum level filters may help.

**Comment by DanielAsher** [comment]
@skreutzberger hi!

would you be able to put a couple of sentences suggesting why this is the case? I'm curious.

I would suggest that multiple log streams allow the developer to express intent at time code is being written, allowing separation of concerns to be an intimate part of the process.

I love the idea of minimum level filters (so much I've created https://github.com/DaveWoodCom/XCGLogger/issues/120), but feel they are ex-post facto and rely on very tight controlled naming conventions.

These features seem to address the same problem, but from very different viewpoints. I believe together they leverage all parts of the development process.

**Comment by skreutzberger** [comment]
Hmmm, since you already suggest it on XCGLogger it seems that it is maybe the logger you anyway prefer.

For me simplicity is key and all programming languages I worked with in the past used a similar one-logger-instance approach. SwiftyBeaver tries to make the start with the Swift programming language as convenient as possible, especially if you are coming from Javascript or Python. 
 
A confusing, not standard (my opinion) multi-instance logger is just making things harder. Additionally, existing installations of SwiftyBeaver would break if we switch to a multi-instance logger AFAIR.

You are the first who did that feature request and if I more users do request it often over the next weeks  then I will reconsider. 

In general, I get your point and it makes sense but it goes against the KISS philosophy of the project. Of course if you could provide an elegant but still simple, back-portable solution in a PR then I would reconsider :)

**Comment by DanielAsher** [comment]
@skreutzberger thanks so much for this reply. It seems a reasonable position to take. I'll keep tabs on the issue myself - let's see how your no doubt happy users respond. Perhaps you would consider reopening the issue for a couple of weeks to gauge opinion:)

**Comment by dboydor** [comment]
I forked this project and implemented an optional label for destinations like:

`let file = FileDestination("SeperateLog")`

Then added an optional "dest" parameters for all log.XXX() methods:

`log.error(dest: "SeperateLog", "This is a bad error!")`

If you don't specify the label, you can use it like it is currently, and everything goes into all the log destinations that don't have a label.

```
let file = FileDestination()
log.error("This is a bad error!"). // Note: this will not be logged in "SeperateLog" above

```
https://github.com/dboydor/SwiftyBeaver

**Comment by xanderdunn** [comment]
I strongly agree that the ability to create multiple loggers would be beneficial. There are portions of a server-side app that become confusing and too verbose when they are logging on top of each other. 

It should be feasible to default to a single global logger instance while still providing the option of creating more than one to advanced users. Setting a boolean on which the singleton checks would be one way to achieve that.

The logger object is not global in my project, so passing a different object to different portions of the code would make a lot of sense. The primary reason I'd like this is to separate concerns. All of the logs for all of the various components of the server on top of each other can make it much more difficult to monitor asynchronous portions of the server. The ability to filter them into separate destinations increases readability of logs through time. Currently the only solution is to make sure every log string has a particular substring on which I can filter. This is error prone and verbose.

**Comment by IsaiahJTurner** [comment]
This project has been potentially breached and your app may be exposing private information. See issue #453

**Comment by skreutzberger** [comment]
@IsaiahJTurner What a troll. WTF is just wrong with you abusing the Github notification system? I have reported you to Github for spam. If you want to advertise for a company or project then please do it the normal way and leave the SwiftyBeaver contributors alone. NOTHING HAS BEEN BREACHED. SwiftyBeaver is an open-source framework and its used encryption is public, known and trusted since several years.
