### ISSUE TITLE
Color coding should be in the ConsoleDestination, not in BaseDestination

### ISSUE THREAD

**Issue by xeo-it** [SwiftyBeaver/SwiftyBeaver#69]
I believe color coding is useful only in the console but not in any other situations.
I would move it to the ConsoleDestination class so that when subclassing BaseDestination the color coding is excluded and the default logs do not include that.
Right now, when writing to a log file, it's necessary to specify *colored=true* otherwise the logs include the color coding and are hard to read.  
If there is a particular reason why the color coding is in the base class, I apologize.

**Comment by skreutzberger** [comment]
Color coding is an option for logging to Xcode Console, file and potential future destinations. Especially for logging to file the colors are very handy. They work  if you use a Terminal application like Mac OS X Terminal.app to tail your logs. Actually that is my currently preferred way of consuming logs.

Due to that the colors should stay in BaseDestination I guess.
