### ISSUE TITLE
Log-file rotation

### ISSUE THREAD

**Issue by skreutzberger** [SwiftyBeaver/SwiftyBeaver#7]
How would you like to have that feature specified?

**Comment by vittoriom** [comment]
Hi @skreutzberger,
sorry if I didn't create this issue yesterday, but I had a pretty busy day.

Nevertheless, let's analyse this issue:

1- A rolling file strategy would mean having a threshold (of size, or time) after which a new file should be created
2- This also means you have to keep track of which and how many files you already store, maybe do some cleanup after a while

In my opinion, the biggest drawback with the approach you implemented now is how big the file can get.
Is there any limit at the moment? Maybe you should put a maximum size (e.g. 10KB or similar), or let the user configure it at least.

What happens after the cap is reached? A new file is started from scratch? I would say just pop the first line every time you need to append a new line. This way the size is always "capped" and you have the most recent logs at hand.

I'm saying this because there are 2 main reasons why one would log to a file in my opinion:
1- Executing the app on a device, it's useful to have a way to inspect the logs after a crash or some unexpected situation
2- Main reason for us: after a crash we want to send the last logs to HockeyApp

This is everything that comes to my mind :) 
Hope you manage to wrap your head around it and find a nice and simple way to have something similar!

**Comment by skreutzberger** [comment]
HI @vittoriom  - thanks a lot for your feedback! You know I love simple ideas so what about that:

- every day a new log file is created
- the date is added to the filename in the format YY-MM-DD
- the developer sets the amount of days he wants to keep the files
- SwiftyBeaver deletes files which are older. Not based on the date in the filename but based on file creation date provided by the operating system.

In that way the user would just need to adjust a single option which would be an integer (amount of days) and SwiftyBeaver would do the rest automagically. Makes sense?

**Comment by vittoriom** [comment]
sort of makes sense, that's the way CleanroomLogger is implemented. 
On the other hand, deciding which log file to send Hockey (after a crash) it's not so immediate (maybe the user didn't open the app for 2 days after the crash, or the crash happened at 23.59 and he opened the app after 2 minutes) and having a single file was slightly easier to handle. But I understand this might make things a bit more complex.
It's your call, after all :)

**Comment by skreutzberger** [comment]
What are other alternatives?

**Comment by vittoriom** [comment]
The only alternative I can come up with is to have a "rolling log", that is a log that works as a queue and throws away older lines for newer lines. 
Not sure how to do that efficiently, since probably working with Swift arrays and popping and pushing elements is slower than optimal, but I didn't investigate too much on this.

**Comment by skreutzberger** [comment]
Implemented & released at 3ccc67ce284

**Comment by skreutzberger** [comment]
I marked the wrong issue as completd, reopening :)

**Comment by prenagha** [comment]
I would leave the deleting of the "old" files out of the logging library
I suggest the purpose of a logging library rotating, is when the active log file is "too old" or "too large", that file gets deactivated and a new log file is started
I would leave file management (clean-up of files) to some process outside the libary - someone may want to archive off system, compress, delete for example. This also removes lots of risk as the logging library would never be deleting anything

**Comment by skreutzberger** [comment]
@prenagha :+1:

**Comment by skreutzberger** [comment]
I put it in the roadmap for 1.1-1.2 which should be released in April/May. In the meantime I am closing the issue and bring it back up when it is time for implementation.

**Comment by georgbachmann** [comment]
Quick question on that one? I had a quick look at `FileDestination` and can't find any kind of rolling-time thing? Is this feature implemented yet? How big would my logfiles get? Also, It seems to be only one logfile (didn't have a detailed look at the code yet, but there is only one URL I get form `FileDestination`)?

I am using file-logging, to log all of the events on a users phone (also during production) and if they have a problem, then there's a way in the app to send us those logs so we can have a look at what was going on...

**Comment by skreutzberger** [comment]
Yes, log file rotation is not built-in and some users have built their own custom solutions. In general, it is recommended to use the platform destination for retrieving release logs. 

Additionally, the log file is stored in caches directory which is auto-wiped when the OS asks for it.

Having said that, it would be cool to have log file rotation in its most simple, easy-to-understand form. Maybe you can set a max file size in the destination and if that is reached then the rotation starts? Do you want to do a pull request?

**Comment by georgbachmann** [comment]
What do you mean by platform destination for retrieving release logs? I don't know that much about logging yet...

I am still in the process of figuring out which logging framework I'll be using... So my question was mainly out of interest. I am currently moving away from CocoaLumberjack (as file logging is pretty broken there) and creating a central place in my app where I can plugin all sorts of different Logging-Frameworks.
If I'll stick to SwiftyBeaver I might further have a look at file-rotation

**Comment by skreutzberger** [comment]
I often hear the user story of a migration from CocoaLumberjack to SwiftyBeaver and I guess its a good, more future-proof and especially more convenient choice 😉

The SwiftyBeaver platform destination sends your logs during development and especially release automagically from your user’s devices through the cloud to the SwiftyBeaver Mac App which lives on your computer.

It removes the need for own send-logfiles-from-users-to-me logic and additionally has end-to-end encryption and a UI that makes searching, filtering and generally browsing of your user logs more convenient.

Here are the docs for the platform destination: [http://docs.swiftybeaver.com/article/11-log-to-swiftybeaver-platform](http://docs.swiftybeaver.com/article/11-log-to-swiftybeaver-platform) and please also have a look at the website which explains all 3 components (framework, cloud & Mac App).

You can also join our Slack community to meet other fellow Swift users and contributors. Free registration is at [http://slack.swiftybeaver.com](http://slack.swiftybeaver.com)

**Comment by georgbachmann** [comment]
I already had a look at the platform but I guess I won't use it. I use logentries to send unexpected Logs (all Error and Warning logs) and all the others are just written to file and we ask our users to send those (which is very easy for them). That works perfectly for me...

Are any of the solutions already written by other open source? Do you know of any?

**Comment by jenjia** [comment]
Is there a timeframe for this feature to be implemented?

**Comment by skreutzberger** [comment]
@jenjia - No but simple PRs are appreciated :)

**Comment by jenjia** [comment]
@skreutzberger - Sorry my ignorance, "PRs"?

**Comment by skreutzberger** [comment]
no problem :)  PRs == pull requests

**Comment by DivineDominion** [comment]
Since this pops up in search result, can anybody point to existing implementations of file rotation?
