### ISSUE TITLE
Printing variable name and value pair

### ISSUE THREAD

**Issue by toshi0383** [SwiftyBeaver/SwiftyBeaver#81]
Hello!!

I thought it'd be useful if we could do like this.

```
let foobar = 1234
SwiftyBeaver.debugObject(foobar) // will prints "foobar = 1234"
```

Inspired by https://github.com/inamiy/DebugLog, which has `LOG_OBJECT`. This works only on Simulators. It fallbacks to `LOG` on devices, and example above will print `"1234"`.

Are you happy to have me add this feature ?

**Comment by skreutzberger** [comment]
It is an interesting but too specific solution. What do the other guys think?

**Comment by davidrothera** [comment]
I am assuming what are you thinking of is printing the object name and then the string convertible of that object's value?

This would work nicely for the built-in types as most of them adhere to the `StringLiteralConvertible` protocol so know how to represent themselves as a string but for other object types it could be pretty useless.

I can still see that it would be a nice addition though and shouldn't change any other code :+1:

**Comment by skreutzberger** [comment]
I checked how I am doing logging in my own code and interestingly I very often just log the value of a variable and add the name to it. So that new feature would help.

But what about the log levels? I would try to avoid to introduce another set of functions a user needs to remember.

What do you think about the following:
if a user just logs a single variable then the logging is not just the output of the variable itself but also the variable name and maybe some additionally interesting data (any ideas?) like if it is a constant or variable, maybe the scope, etc.

So a call like `log.debug(foobar)` would result in a log message of `foobar = 1234`

Makes sense or is it a too unexpected behavior?

**Comment by davidrothera** [comment]
Hmm...

I think that as long as you gate the change with something in the config it should be ok to make it so that if you are just logging a single object to do the "name -> value" print.

I am just wary of changing the API under people.

The other way, which as you said would require more functions would be to have like:

```swift
log.debugObject(object_to_print)
```

I agree though that adding more functions is a difficult decision to make.

**Comment by skreutzberger** [comment]
thanks for the feedback! Then let’s maybe postpone that for later when we think that we need a more debugger-styled logging output. The idea itself is good but it adds extra learning and complexity in getting started with SwiftyBeaver.

Many / most(?) users really like that SwiftyBeaver is an easy-to-learn but mighty multi-purpose / generic tool and we should stick to keeping it simple.

I am closing the discussion for now but let’s keep it in mind. Having a strong debug output would be interesting but if we do it then we should do it really thoroughly, maybe like an inspector or so.
