### ISSUE TITLE
Praise, request and a question

### ISSUE THREAD

**Issue by mohpor** [SwiftyBeaver/SwiftyBeaver#96]
### Praise
First off, how did we live prior to `SwiftyBeaver`? Seems impossible to live without now!

### Request
It would be awesome to hide or delete log items? logs will grow beyond control after a while.

### Question

~~When I try to log to `SBPlatformDestination`, it won't be flushed until my next launch! is it intentional? Am I missing something? They don't appear on SwiftBeaver Mac App until my iOS apps next launch.~~ Got it, it was the threshold thing!

**Comment by skreutzberger** [comment]
Thanks for the praise! Hiding, archiving, or deleting of logs is coming soon. In the meantime feel free to create a new app whenever you release a new version. It is working because you can have multiple SwiftyBeaver Mac Apps open and the analytics statistics stay the same because they are device-based.

Tip: join our Slack channel at [https://slack.swiftybeaver.com]( https://slack.swiftybeaver.com) to discuss with contributors and users.
